meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: al_broker
    templates:
    - name: al_broker
      release: al_broker
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set al_broker networks" ))

networks: (( param "please set networks" ))

properties:
  al_broker:
    listening_port: 8080
    destination_port: 80
    destination_url: http://10.244.3.46
