meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: al_broker
    templates:
    - name: al_broker
      release: al_broker
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set al_broker networks" ))
  - name: mock_catalog_service
    templates:
    - name: mock_catalog_service
      release: al_broker
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set mock_catalog_service networks" ))

networks: (( param "please set networks" ))

properties:
  mock_catalog_service:
    port: 8000
  al_broker:
    port: 8080
    service_broker_port: 80
    service_broker_url: http://10.244.25.2
    destination_port: 80
    destination_url: http://10.244.25.3
